version: "3"

services:
  image-storage:
    build: ./image-storage
    container_name: image-storage
    environment:
      - FLASK_ENV=dev
    volumes:
      - "./image-storage:/code"
  image-transforms:
    build: ./image-transforms
    container_name: image-transforms
    volumes:
      - "./image-transforms:/code"
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:8080"
